spring:
  application:
    name: aadhaar-esign
  profiles:
    active: DEV
  datasource:
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 60s
server:
  shutdown: "graceful"

logging:
  level:
    "org.springframework.jdbc.core": DEBUG
  file:
    name: aadhaar-esign.log
    path: ./logs
  logback: 
    rollingpolicy: 
      max-history: 10
      max-file-size: 100MB
      total-size-cap: 1GB

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  info:
    git:
      mode: full
  metrics:
    enable:
      jvm: true
      system: true

#metrics
#spring.metrics.enable-jvm=true
#spring.metrics.enable-system=true